name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on:  ubuntu-latest
    steps:
      - name: Print Hello
        run: |
          echo "Welcome to GitHub Actions"
          echo "Printing Second echo command "
      - name: Print GoodBye
        run:  echo "Done - Good Bye!!"
    
